### ISSUE TITLE
Bad link on README

### ISSUE THREAD

**Issue by refi64** [flower/fvm#1]
The commit logs seem to portray that this project is being rewritten in C++. If so, a note in the README would be nice; the invalid links to the instruction set and contributing guide are not very informative. :)

**Comment by phase** [comment]
I've restarted the project in C++, and the Instruction is being rewritten to go along with the Stack based VM. I'll write one up at a later date.

**Comment by chibill** [comment]
Okay. Also you might want to fix the link in the organization for power's site as there is no site..
